default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/dev_db

test:  
  <<: *default
  database: db/test_db

production:
  <<: *default
  database: db/production_db
