# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a4b974cadb648b78b564a00cf62fcdd7bcaf0e4a0fa11be5515711d10164524e7c121a79e70ef111f3f6c7478af483d50582022b043c03d0c36244dee73c74d

test:
  secret_key_base: 2a8a08d44b2dbc28fcfcb9a2364a6a78685f67e1b7a125986a7f3e5abf5af35d2dfdcb6a889d2c6325c7e5e9d441ba873b8ab89e4707cb742662502bab651fee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
